# Spring properties
spring:
  application:
    name: task-service  # Identify this application
  
# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
      
eureka:
  instance:
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    preferIpAddress: true  
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 1
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1    

# HTTP Server
server:
  port: 0   # HTTP (Tomcat) port