#== Spring properties ==
spring:
  application:
    name: zuul-server  # Identify this application
  
#== Map the error path to error template (for Thymeleaf) ==
error:
  path=/error

#=== Discovery Server Access ==

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

#=== Zuul Configuration =====

zuul:
  ignoredServices: "*"
  routes:
    user-service: /userService/**
    task-service: /taskService/**
    auth-server: /authServer/**

#=== HTTP Server ===

server:
  port: 4444   # HTTP (Tomcat) port

# === Logging ===

logging:
  level:
    root: WARN
   


